name: whisker-test

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  whisker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress tests
        env:
          CYPRESS_WHISKER_URL: ${{ vars.CYPRESS_WHISKER_URL }}
        runs: |
          echo $CYPRESS_WHISKER_URL

      - name: Cypress tests
        env:
          CYPRESS_WHISKER_URL: ${{ vars.CYPRESS_WHISKER_URL }}
        uses: cypress-io/github-action@v5
        with:
          build: npx cypress info