name: whisker-test

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  basic-ubuntu-22-v9:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress tests
        env:
          CYPRESS_WHISKER_URL: env.CYPRESS_WHISKER_URL
        uses: cypress-io/github-action@v5
        with:
          build: npx cypress info