name: whisker-test

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    - cron: '* 16 * * *'

jobs:
  whisker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress tests
        env:
          CYPRESS_WHISKER_URL: ${{ vars.CYPRESS_WHISKER_URL }}
        uses: cypress-io/github-action@v5
